In [1]:
#hide

In [2]:
#hide
import utils
utils.hero("Getting To Know 'float' Better")

In [3]:
#hide
utils.h1("Numerical Representation")

Numerical representation is used to describe measurable quantities. To store them in memory, we have dedicated built-in dataypes in python. \
These data types are:
1. int: For storing integer values
2. float: For storing decimal values

In [4]:
#hide
utils.note("Numbers can also be stored as word (string) by treating each digit as characters but you will not be able to use built-in operations defined for int/float")

In [5]:
#hide
utils.h1("Important information about data type")

For any datatype, one must know these information about them:
1. How to create an object/instance of a data type class?
2. How much memory does it consume?
3. How to find out the memory location where it is stored?
4. Can you make changes in the data once created? (Mutable and Immutable datatypes)
5. What are the common methods that can be applied to the value?
6. How is it represented internally? (small integer caching, string interning)
7. Is it iterable or indexable?

We will answer these questions for each of the data types.

In [6]:
#hide
utils.h1("Float")

In [7]:
#hide
utils.h2("Declaration")

In [8]:
# Declaration
a = 10.9 # Literal declaration, no additional overhead
print(f"{a} {type(a)}")
# OR 
b = float(10.9) # Calling the constructor, additional overhead
print(f"{b} {type(b)}")
print("-"*100)

10.9 <class 'float'>
10.9 <class 'float'>
----------------------------------------------------------------------------------------------------


In [9]:
#hide
utils.important("The variable 'a' and 'b' only stores the memory location of the objects and the values itself")

In [10]:
#hide
utils.tip("Use literal declaration unless intended for type conversion")

In [11]:
#hide
utils.h2("Finding Memory Consumption")

In [12]:
# To find the memory consumption, we can use "sys" module
import sys
print(f"Memory used by the object a={a} is {sys.getsizeof(a)} bytes")
print(f"Memory used by the object b={b} is {sys.getsizeof(b)} bytes")

# For some built-in datatypes we also have a method '__sizeof__' that gives us the size excluding (garbage collector overhead)
print(f"Memory used by the object a={a} is {a.__sizeof__()} bytes")
print(f"Memory used by the object b={b} is {b.__sizeof__()} bytes")
print("-"*100)

Memory used by the object a=10.9 is 24 bytes
Memory used by the object b=10.9 is 24 bytes
Memory used by the object a=10.9 is 24 bytes
Memory used by the object b=10.9 is 24 bytes
----------------------------------------------------------------------------------------------------


In [13]:
#hide
utils.important("In Python, the built-in float type is implemented as a C double. \
It uses a fixed amount of memory, so its precision is limited and cannot grow dynamically unlike int")

In [14]:
#hide
utils.exercise("Find the size of integer ranging from 1e0, 1e-1, ..., to 1e-100")

In [15]:
# Your solution

In [16]:
# Solution
import sys

vals = [10**(-val) for val in range(10, 100, 10)] # [1e-10, 1e-20, 1e-30, ...] (all float type)

for val in vals:
    print(f"{val:.2e} ({type(val)}) || Memory: {sys.getsizeof(val)} bytes")
print("-"*100)

1.00e-10 (<class 'float'>) || Memory: 24 bytes
1.00e-20 (<class 'float'>) || Memory: 24 bytes
1.00e-30 (<class 'float'>) || Memory: 24 bytes
1.00e-40 (<class 'float'>) || Memory: 24 bytes
1.00e-50 (<class 'float'>) || Memory: 24 bytes
1.00e-60 (<class 'float'>) || Memory: 24 bytes
1.00e-70 (<class 'float'>) || Memory: 24 bytes
1.00e-80 (<class 'float'>) || Memory: 24 bytes
1.00e-90 (<class 'float'>) || Memory: 24 bytes
----------------------------------------------------------------------------------------------------


In [17]:
#hide
utils.h2("Finding Memory Location")

In [18]:
# To find the memory location of an object, we have a built-in function in python called 'id'
a = 10.9
print(f"'a' points to {id(a)} | {hex(id(a))}")
print("-"*100)

'a' points to 4428430384 | 0x107f47c30
----------------------------------------------------------------------------------------------------


In [19]:
#hide
utils.exercise(f"Given the memory location {hex(id(a))}, how can you find the value stored in that location?")

In [20]:
# Your solution (hint: Use ctypes module)

In [21]:
# Solution

import ctypes
value = ctypes.cast(obj=id(a), typ=ctypes.py_object).value # This is only for demonstration, use it extreme caution to avoid crash
print(value, type(value))
print("-"*100)

10.9 <class 'float'>
----------------------------------------------------------------------------------------------------


In [22]:
#hide
utils.h2("Mutable/Immutable?")

Everything we declare in Python is an object. By object, I mean an instance of a defined 'class'. \
When you create an object and assign it to a variable, the variable stores the memory location of the object or we say the variable points to the object. If the object at that memory location can be modified during runtime then the object and the associated data type is said to be **mutable** otherwise **immutable**.

In [39]:
a = 10.9
print(f"Variable 'a' points to {id(a)} where the stored value is {a}")
a = 20.9
print(f"Variable 'a' points to {id(a)} where the stored value is {a}")
print("-"*100)

Variable 'a' points to 4428430224 where the stored value is 10.9
Variable 'a' points to 4428430320 where the stored value is 20.9
----------------------------------------------------------------------------------------------------


In [41]:
#hide
utils.question("What happened when we changed the value of a to 20.9? Is 'float' mutable?")

No, 'float' is immutable even though it seems like we managed to change the value (from 10.9 to 20.9) but under the hood when we tried to change the value by reassigning 'a' to 20.9, it actually created a new object(20.9) at a different memory location and then 'a' started pointing to the new object(20.9)

In [42]:
#hide
utils.exercise("Find out the value stored at the memory location that 'a' was pointing before reassigning")

In [26]:
# Your solution

In [27]:
#
utils.h2("Available Methods for Int")

In [28]:
#hide
utils.tip("To find out all the parameters and methods available to an object, Python provides us 'dir' or '__dir__' that returns a list \
of all such parameters and methods")

In [29]:
a = 50.4
print(dir(a))
print("-"*100)

['__abs__', '__add__', '__bool__', '__ceil__', '__class__', '__delattr__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floor__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getformat__', '__getnewargs__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__int__', '__le__', '__lt__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__pos__', '__pow__', '__radd__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rmod__', '__rmul__', '__round__', '__rpow__', '__rsub__', '__rtruediv__', '__setattr__', '__sizeof__', '__str__', '__sub__', '__subclasshook__', '__truediv__', '__trunc__', 'as_integer_ratio', 'conjugate', 'fromhex', 'hex', 'imag', 'is_integer', 'real']
----------------------------------------------------------------------------------------------------


In [30]:
#hide
utils.exercise("Try out some of the methods from the list!")

In [31]:
# Your solution

In [32]:
# Solution

In [43]:
#hide
utils.h2("Small Float Caching?")

In [34]:
a = 0.01
print(f"Varaible a points at {id(a)} which has {a}")
b = 0.01
print(f"Varaible b points at {id(b)} which has {b}")
print("-"*100)

Varaible a points at 4428422928 which has 0.01
Varaible b points at 4428430576 which has 0.01
----------------------------------------------------------------------------------------------------


Based on above, we observe that both 'a' and 'b' points to different address. Python **does not** cache float objects unlike small int objects.

In [35]:
#hide
utils.h2("Iterable and Indexable?")

A datatype is said to be **Iterable** if it implements either of the methods:
1. \_\_iter\_\_(): returns an iterator
2. \_\_getitem\_\_(): with integer indices starting from 0

A datatype is said to be **indexable**:
- **by integer** if it implements \_\_getitem\_\_(index)
- **by key** if it implements \_\_getitem\_\_(key)

In [36]:
#hide
utils.tip("'collections' module in Python can be used to find out if an object is iterable")

In [37]:
# Code to check if an object is iterable and indexable
def is_iter_indexable(obj):
    from collections.abc import Iterable
    is_iterable = isinstance(obj, Iterable)
    is_indexable = hasattr(obj, "__getitem__")
    print(f"{type(obj)}   Iterable: {is_iterable} || Indexable: {is_indexable}")

is_iter_indexable(10.9)

<class 'float'>   Iterable: False || Indexable: False


In [38]:
#hide
utils.upcoming("We will look into another datatype 'string'")